# Generated by Django 2.0 on 2022-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '测试图片',
                'verbose_name_plural': '测试图片',
                'db_table': 'userprofile',
            },
        ),
    ]
